### ISSUE TITLE
Add Stripe Payment Processing Component

### ISSUE THREAD

**Issue by Jared-Dev** [oc-shopaholic/oc-omnipay-shopaholic-plugin#2]
It would be nice if there was a component built to process payments via Stripe.

**Comment by InquisitiveDevelopment** [comment]
Added a bounty for the amount that I'd be willing to pay for this plugin on [BountyHunter](https://www.bountysource.com/issues/58256992-add-stripe-payment-processing-component)

**Comment by vdomah** [comment]
@Jared-Dev hi, added new plugin to the marketplace that solves this issue: [Stripe for Shopaholic](https://octobercms.com/plugin/vdomah-stripeshopaholic)

**Comment by lautsevich** [comment]
Hi @Jared-Dev.

Sorry for the very long delay. As @vdomah mentioned, he published a separate plugin that solves this issue. This plugin is verified and recommended by the Shopaholic team.
