### ISSUE TITLE
Can't see Settings

### ISSUE THREAD

**Issue by coycash** [oc-shopaholic/oc-omnipay-shopaholic-plugin#8]
I'm not able to see the Payment Gateway settings on the Payment Methods page.  I just see Name, Code & Description unlike the screenshot.

I did have to revert the following to 2.8 to get omnipay to install successfully
`"symfony/event-dispatcher": "^2.8",`

Not sure how to debug this since I'm not seeing anything

**Comment by kharanenka** [comment]
Hi! You need debug \Lovata\OmnipayShopaholic\Classes\Helper\PaymentGateway::getOmnipayGatewayList() method. Method returns omnipay gateways. Method used in backend to display a list of available payment gateways.
